In [2]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("dataset\\train_u6lujuX_CVtuZ9i.csv")

In [4]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [7]:
# Checking if there are any missing values in any of the features
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [9]:
cols = ['Gender','Married','Dependents','Self_Employed','Loan_Amount_Term','Credit_History']

for c in cols:
    df[c].fillna(df[c].mode()[0], inplace=True)

df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)

C:\Users\Shikhaj Somani\AppData\Local\Temp\ipykernel_19644\3855781719.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[c].fillna(df[c].mode()[0], inplace=True)
C:\Users\Shikhaj Somani\AppData\Local\Temp\ipykernel_19644\3855781719.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a c

In [10]:
# Filled all the missing values
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cat_cols = ['Gender','Married','Dependents','Education','Self_Employed','Property_Area']

for c in cat_cols:
    df[c] = le.fit_transform(df[c])

df['Loan_Status'] = le.fit_transform(df['Loan_Status'])


In [12]:
# Independent Features
X = df[['Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area']]

# Dependent Feature
y = df['Loan_Status']

In [13]:
X.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0             5849   
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2

In [14]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

In [15]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [16]:
X_train

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
260       1        1           1          0              0             6083   
303       1        1           1          0              0             1625   
407       0        0           0          1              0             2213   
261       1        0           0          0              0             2060   
352       1        1           3          0              0             2666   
..      ...      ...         ...        ...            ...              ...   
369       1        1           0          0              0            19730   
320       1        1           0          0              0             2400   
527       1        1           1          1              0             5285   
125       0        0           0          0              0             3692   
265       1        0           0          0              0             4095   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
260             4250.0       330.0             360.0             1.0   
303             1803.0        96.0             360.0             1.0   
407                0.0        66.0             360.0             1.0   
261             2209.0       134.0             360.0             1.0   
352             2083.0        95.0             360.0             1.0   
..                 ...         ...               ...             ...   
369             5266.0       570.0             360.0             1.0   
320             2167.0       115.0             360.0             1.0   
527             1430.0       161.0             360.0             0.0   
125                0.0        93.0             360.0             1.0   
265             3447.0       151.0             360.0             1.0   

     Property_Area  
260              2  
303              2  
407              0  
261              1  
352              0  
..             ...  
369              0  
320              1  
527              1  
125              0  
265              0  

[491 rows x 11 columns]

In [17]:
y_test

285    1
323    1
482    1
173    1
518    0
      ..
554    0
6      1
242    1
192    0
157    1
Name: Loan_Status, Length: 123, dtype: int64

In [18]:
# Standardization 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [19]:
nums_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount']

X_train[nums_cols] = scaler.fit_transform(X_train[nums_cols])
X_test[nums_cols] = scaler.transform(X_test[nums_cols])

In [20]:
X_train

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
260       1        1           1          0              0         0.075399   
303       1        1           1          0              0        -0.598270   
407       0        0           0          1              0        -0.509414   
261       1        0           0          0              0        -0.532535   
352       1        1           3          0              0        -0.440960   
..      ...      ...         ...        ...            ...              ...   
369       1        1           0          0              0         2.137660   
320       1        1           0          0              0        -0.481156   
527       1        1           1          1              0        -0.045190   
125       0        0           0          0              0        -0.285916   
265       1        0           0          0              0        -0.225017   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
260           0.825530    2.068089             360.0             1.0   
303           0.048356   -0.605934             360.0             1.0   
407          -0.524281   -0.948757             360.0             1.0   
261           0.177303   -0.171691             360.0             1.0   
352           0.137285   -0.617361             360.0             1.0   
..                 ...         ...               ...             ...   
369           1.148214    4.810676             360.0             1.0   
320           0.163964   -0.388813             360.0             1.0   
527          -0.070109    0.136850             360.0             0.0   
125          -0.524281   -0.640216             360.0             1.0   
265           0.570495    0.022576             360.0             1.0   

     Property_Area  
260              2  
303              2  
407              0  
261              1  
352              0  
..             ...  
369              0  
320              1  
527              1  
125              0  
265              0  

[491 rows x 11 columns]

In [21]:
# Training different models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [22]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [24]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [25]:
# Make predictions
y_pred_lr = lr.predict(X_test)
y_pred_knn = knn.predict(X_test)
y_pred_dt = dt.predict(X_test)

In [26]:
# Performance Metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
# Logistic Regression Performance
print(accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

0.7967479674796748
[[12 24]
 [ 1 86]]
              precision    recall  f1-score   support

           0       0.92      0.33      0.49        36
           1       0.78      0.99      0.87        87

    accuracy                           0.80       123
   macro avg       0.85      0.66      0.68       123
weighted avg       0.82      0.80      0.76       123



In [28]:
# KNN Performance
print(accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

0.6991869918699187
[[10 26]
 [11 76]]
              precision    recall  f1-score   support

           0       0.48      0.28      0.35        36
           1       0.75      0.87      0.80        87

    accuracy                           0.70       123
   macro avg       0.61      0.58      0.58       123
weighted avg       0.67      0.70      0.67       123



In [29]:
# Decision Tree Performance
print(accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

0.7235772357723578
[[19 17]
 [17 70]]
              precision    recall  f1-score   support

           0       0.53      0.53      0.53        36
           1       0.80      0.80      0.80        87

    accuracy                           0.72       123
   macro avg       0.67      0.67      0.67       123
weighted avg       0.72      0.72      0.72       123



In [32]:
# GridSearchCV Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV

In [33]:
params = {
    'C': [0.01, 0.1, 1, 5, 10, 50, 100],
    'solver': ['liblinear', 'lbfgs', 'newton-cg', 'saga'],
    'penalty': ['l1', 'l2', 'elasticnet'],
    'max_iter': [200, 500, 800]    
}

In [35]:
grid = GridSearchCV(estimator=lr, param_grid=params, scoring='accuracy', cv=5, n_jobs=-1)

In [37]:
import warnings
warnings.filterwarnings('ignore')
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 5, 10, 50, 100],
                         'max_iter': [200, 500, 800],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['liblinear', 'lbfgs', 'newton-cg', 'saga']},
             scoring='accuracy')

In [38]:
grid.best_params_

{'C': 0.1, 'max_iter': 200, 'penalty': 'l2', 'solver': 'liblinear'}

In [41]:
print(grid.best_score_)

0.8146773861059575


In [43]:
# GridSearchCV Performance Metrics
y_pred_grid = grid.predict(X_test)
print(accuracy_score(y_test, y_pred_grid))
print(confusion_matrix(y_test, y_pred_grid))
print(classification_report(y_test, y_pred_grid))

0.7967479674796748
[[12 24]
 [ 1 86]]
              precision    recall  f1-score   support

           0       0.92      0.33      0.49        36
           1       0.78      0.99      0.87        87

    accuracy                           0.80       123
   macro avg       0.85      0.66      0.68       123
weighted avg       0.82      0.80      0.76       123



In [46]:
# Saving the model so dont need to retrain everytime
import joblib
joblib.dump(lr, 'loan_prediction.pkl')

['loan_prediction.pkl']